baseURL = "http://vincent.github.io/gites/fr/"
languageCode = "en-us"
title = "Gîtes en Sologne"
theme = "sodium"
publishDir = "docs"

defaultContentLanguage = "fr"
enableMissingTranslationPlaceholders = "true"


[languages]
    [languages.fr]
        baseURL = "https://vincent.github.io/gites/fr/"
        code = "fr"
        languageName = "Français"
        title = "Gîte en Sologne"
        weight = 1
    [languages.en]
        baseURL = "https://vincent.github.io/gites/en/"
        code = "en"
        languageName = "English"
        title = "Sologne's country homes"
        weight = 2

[params]
    [params.cover]
        image = "flower3.jpg"
        [params.cover.button]
            text = "Contact"
            href = "/#contact"

    [params.contact]
        address = "26, rue des Prés"
        address2 = "41210 Neung sur Beuvron"
        phone = "02 54 83 66 67"
        email = "anthony.lark@laposte.net"

    [params.village]
        id = "village"
        title = "Le village"
        cover = "images/gites/cover-village.jpg"
        description = "Catch phrase pour village"
        [[params.village.content]]
            icon = "bell"
            title = "Feature 1"
            description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam elementum tristique arcu, in tristique sapien commodo sodales. Vivamus condimentum quam mi."
        [[params.village.content]]
            icon = "rocket"
            title = "Feature 2"
            description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam efficitur, est sed vestibulum viverra, mi dui semper erat, non placerat dolor est"
        [[params.village.content]]
            icon = "clock"
            title = "Feature 3"
            description = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus in ornare orci, et posuere velit. Suspendisse tempor blandit augue, non. "

    [params.gites]
        [params.gites.alouettes]
            id = "alouettes"
            title = "Les Alouettes"
            cover = "images/gites/cover-alouettes.jpg"
            description = "Catch phrase pour Les Alouettes"
            url = "http://www.gites-de-france-blois.com/location-vacances-gite-a-neung-sur-beuvron--gites41_b2012.1.G758.G.html"
            [[params.gites.alouettes.content]]
                icon = "users"
                title = ""
                description = ""
                bullets = [
                    "6 personnes",
                    "3 chambres",
                    "81 m²"
                ]
            [[params.gites.alouettes.content]]
                icon = "bed"
                title = ""
                description = ""
                bullets = [
                    "Cheminée",
                    "Lave-linge",
                    "Lave-vaisselle",
                    "Micro-ondes",
                    "Télévision"
                ]
            [[params.gites.alouettes.content]]
                icon = "clock"
                title = ""
                description = ""
                bullets = [
                    "Télévision",
                    "Barbecue",
                    "Salon de jardin"
                ]
        [params.gites.hirondelles]
            id = "hirondelles"
            title = "Les Hirondelles"
            cover = "images/gites/cover-hirondelles.jpg"
            description = "Catch phrase pour Les hirondelles"
            url = "http://www.gites-de-france-blois.com/location-vacances-gite-a-neung-sur-beuvron--gites41_b2012.1.G758.G.html"
            [[params.gites.hirondelles.content]]
                icon = "users"
                title = ""
                description = ""
                bullets = [
                    "6 personnes",
                    "3 chambres",
                    "85 m²"
                ]
            [[params.gites.hirondelles.content]]
                icon = "bed"
                title = ""
                description = ""
                bullets = [
                    "Cheminée",
                    "Lave-linge",
                    "Lave-vaisselle",
                    "Micro-ondes",
                    "Télévision"
                ]
            [[params.gites.hirondelles.content]]
                icon = "clock"
                title = ""
                description = ""
                bullets = [
                    "Télévision",
                    "Barbecue",
                    "Salon de jardin"
                ]

        [params.gites.pierrette]
            id = "pierrette"
            title = "La Pierrette"
            cover = "images/gites/cover-pierrette.jpg"
            description = "Catch phrase pour La Pierrette"
            url = "http://www.gites-de-france-blois.com/location-vacances-gite-a-neung-sur-beuvron--gites41_b2012.1.G758.G.html"
            [[params.gites.pierrette.content]]
                icon = "users"
                title = ""
                description = ""
                bullets = [
                    "2 personnes",
                    "1 chambre",
                    "27 m²"
                ]
            [[params.gites.pierrette.content]]
                icon = "bed"
                title = ""
                description = ""
                bullets = [
                    "Lave-linge",
                    "Micro-ondes",
                    "Barbecue"
                ]
            [[params.gites.pierrette.content]]
                icon = "clock"
                title = ""
                description = ""
                bullets = [
                    "Terrasse",
                    "Barbecue",
                    "Salon de jardin"
                ]
